// Central list of supported languages.
// value      = ISO 639-1 code (matches translation API + backend)
// label      = shown in UI dropdown
// speechCode = BCP-47 code used by the browser's text-to-speech engine
export const LANGUAGES = [
  { value: 'auto', label: 'Detect Language', speechCode: 'en-US' },
  { value: 'en', label: 'English', speechCode: 'en-US' },
  { value: 'es', label: 'Spanish', speechCode: 'es-ES' },
  { value: 'fr', label: 'French', speechCode: 'fr-FR' },
  { value: 'de', label: 'German', speechCode: 'de-DE' },
  { value: 'hi', label: 'Hindi', speechCode: 'hi-IN' },
  { value: 'kn', label: 'Kannada', speechCode: 'kn-IN' },
  { value: 'ta', label: 'Tamil', speechCode: 'ta-IN' },
  { value: 'te', label: 'Telugu', speechCode: 'te-IN' },
  { value: 'mr', label: 'Marathi', speechCode: 'mr-IN' },
  { value: 'bn', label: 'Bengali', speechCode: 'bn-IN' },
  { value: 'gu', label: 'Gujarati', speechCode: 'gu-IN' },
  { value: 'pa', label: 'Punjabi', speechCode: 'pa-IN' },
  { value: 'ur', label: 'Urdu', speechCode: 'ur-PK' },
  { value: 'ja', label: 'Japanese', speechCode: 'ja-JP' },
  { value: 'zh', label: 'Chinese (Simplified)', speechCode: 'zh-CN' },
  { value: 'zh-TW', label: 'Chinese (Traditional)', speechCode: 'zh-TW' },
  { value: 'ko', label: 'Korean', speechCode: 'ko-KR' },
  { value: 'ar', label: 'Arabic', speechCode: 'ar-SA' },
  { value: 'ru', label: 'Russian', speechCode: 'ru-RU' },
  { value: 'pt', label: 'Portuguese', speechCode: 'pt-PT' },
  { value: 'it', label: 'Italian', speechCode: 'it-IT' },
  { value: 'nl', label: 'Dutch', speechCode: 'nl-NL' },
  { value: 'tr', label: 'Turkish', speechCode: 'tr-TR' },
  { value: 'vi', label: 'Vietnamese', speechCode: 'vi-VN' },
  { value: 'th', label: 'Thai', speechCode: 'th-TH' },
  { value: 'id', label: 'Indonesian', speechCode: 'id-ID' },
  { value: 'ms', label: 'Malay', speechCode: 'ms-MY' },
  { value: 'pl', label: 'Polish', speechCode: 'pl-PL' },
  { value: 'uk', label: 'Ukrainian', speechCode: 'uk-UA' },
  { value: 'el', label: 'Greek', speechCode: 'el-GR' },
  { value: 'he', label: 'Hebrew', speechCode: 'he-IL' },
  { value: 'sv', label: 'Swedish', speechCode: 'sv-SE' },
  { value: 'fi', label: 'Finnish', speechCode: 'fi-FI' },
  { value: 'no', label: 'Norwegian', speechCode: 'nb-NO' },
  { value: 'da', label: 'Danish', speechCode: 'da-DK' },
  { value: 'cs', label: 'Czech', speechCode: 'cs-CZ' },
  { value: 'ro', label: 'Romanian', speechCode: 'ro-RO' },
  { value: 'hu', label: 'Hungarian', speechCode: 'hu-HU' },
  { value: 'sw', label: 'Swahili', speechCode: 'sw-KE' },
  { value: 'fa', label: 'Persian', speechCode: 'fa-IR' },
];